// <auto-generated />
namespace WebAccountantASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Cleanallthetables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cleanallthetables));
        
        string IMigrationMetadata.Id
        {
            get { return "202011052120534_Clean all the tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
